### ISSUE TITLE
FiSpace experimentation environment

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#10]
It seems it is down the last couple of week. Any news on when it will be available again?
Are there any alternative sites we can test / experiment with the FISpace platform?

**Comment by rapw3k** [comment]
Hi @vangelisv I dont see any problems with FIspace. Can you explain in more details your problem? Have you tried from different networks?

**Comment by vangelisv** [comment]
I login and the browser waits forever on a almost blank screen (Bottom right reads "2013-2014 ©FISpace. Official FIspace EU")
Page loading never completes, stays with "Transferring data from 37.131.251.117" 

No I have not tried from another network, just from office.

**Comment by rapw3k** [comment]
Could you please try on another network, because I cannot see any problem from my location.

**Comment by vangelisv** [comment]
Now (just now) it worked. As I've mentioned before, I had this problem for at least 10 days... I was thinking that a new version of the environment was being deployed..
