### ISSUE TITLE
Fispace's EE

### ISSUE THREAD

**Issue by pkarkazis** [SAF2/documentation#11]
Hello, I have some questions regarding EE of Fispace:
1. I have uploaded an application in experimental environment (http://37.131.251.117:8080/gui/fispace/main/wirecloud) consisting of some (widgets and operators), when one of my operators tries to make a call to a REST api, hosted in an external server, I get an HTTP error (502 BAD Gateway - http://37.131.251.130:8088/cdp/http/rest_api_path). It seems that the fispace  does not forwards the http request to the external server, because I deployed the same app in FIWARE Lab and worked fine. Am I missing something in this procedure?
2. I  created an new capability in sdi and a business process through EE (http://37.131.251.117:8080/gui/fispace/options/businessCapabilities).  My capability has uri pointing in an external server ({"capability":{"id":18,"description":"Send_Sensor_vals","uri":"http://my_ip:my_port/v1/sections/","cte_id":2}}) but  when try to post data (http://37.131.251.117:8080/sdi/api/capabilities/receive_sensor_values/18) through this capability I get  an error: 404 Server Error. 
3. I am trying to find a tutorial describing how can I define a simple business in order to test it in EE of Fispace (http://37.131.251.156:8080/AcsiWeb/AcsiEditor.html). Is something like that available?

KR
Panos

**Comment by JanWillemKruize** [comment]
Hi, 

I put your question on the FIspace Bitbucket support and received a question back regarding point 1:

When you say "one of my operators tries to make a call" what do you mean exactly? are "wiring" option being used?

Please check:  
https://bitbucket.org/fispace/phase3support/issue/12/fispace-expermination-environment 

Could you clarify this point? 

BR, 

Jan Willem

**Comment by JanWillemKruize** [comment]
For question 3: Did you check the tutorial on B2B on the FIspace website: http://fispace.eu/tutorials.html there you can find the PPT as well.

**Comment by JanWillemKruize** [comment]
For question 2:

The instruction to invoke the capability should look like this: POST to http://37.131.251.117:8080/sdi/api/capabilities/receive_sensor_values/user 

See as well: https://bitbucket.org/fispace/phase3support/issue/13/capability-not-available

**Comment by JanWillemKruize** [comment]
Has this issue now been resolved?

**Comment by pkarkazis** [comment]
Unfortunately, the issue (question 2) remains open. I have managed to define a define a new capability and a business process through EE, but I still have problems with BCM configuration. Also, I follow Diedo's issue in bitbucket (https://bitbucket.org/fispace/apps/issue/95), who is facing the same problems with me, but without successful results. I think that beside the "Business Architect Guide", it is neccessary to provide a step by step procedure describing the SDI and BCM configuration.

**Comment by JanWillemKruize** [comment]
Remaining issue duplicated #12, closing this one since #12 OP is involved in issue also in FIspace side.
