### ISSUE TITLE
SDI example

### ISSUE THREAD

**Issue by diegoguidotti** [SAF2/documentation#12]
In the FISpace Experimentation environment I am not able to find any capabilities except the one I have (tried) to create.

I think that we need 1 sample working capabilities to call to start to test the working of the platform. 

I know that there are one example ( https://bitbucket.org/perezdf/open-owm-adapter) but it require a setup of a local insfrrastructure that require a lot of time (JDK, Jetty, Maven, Next, SDI setup...) and it works only locally. 

The only reason of use FISpace is to call "other" services, we shuld have some online working services to call.

**Comment by diegoguidotti** [comment]
Any reply? it exists a working API in the Experimentation environment to be used for testing?

**Comment by rapw3k** [comment]
Hi Diego, 
I think Jan will be able to give you some feedback quickly, however I have also posted your question to FISPACE ticketing system for accelerators https://bitbucket.org/fispace/phase3support/issue/17/sdi-example

**Comment by JanWillemKruize** [comment]
Hi Diego, 

Sorry for the late responds. I will try to figure it out as soon as posibe. 

Please note that the experimentation environment is only there for experimentation, the platform is not yet in a final state which will include capabilities that can be connected and can be called.

**Comment by diegoguidotti** [comment]
We should, in one week, to define in a project milestone what Fiware/Fispace technologies we have tested and ready to use. Our prototypes should be finished in a few months, if the platform is not ready we should have an official comunication about the future deadline, otherwise we risk to fail our project.

**Comment by JanWillemKruize** [comment]
What kind of external capabilities do you aim to call, based upon your proposal? At this moment the system allows you to check your own capabilities.

**Comment by diegoguidotti** [comment]
My project is smartIPM and I am working on crop protection. It would be great to user the weatherProvider,  and , in general, all APIs from "CROP PROTECTION INFORMATION SHARING" . A lot of SAF project are planning to provide and to consume weather daat it would be great to use FISpace to produce mashup apps.  

Best,
Diego

**Comment by rapw3k** [comment]
Hi @diegoguidotti ,

I assume you have tracked the bitbucket issue. Just in case I am pasting here the replies

"Right now you can only see the capabilities that you have created, that is becaused capabilities are assigned to a user. If you would like you use other people capabilities, you will have to contact the person who have created the capability in order to provide you the id of the capabilitiy that you want to use. At least in EE, in future version of the platform it has to be considered to remove this limitation."

"In order to "communicate" two resources, you will need to define a business process in the BCM, Moti Nisenson can support you on this. The example you refer to, shows how use the capablity model in terms of capabilties definition and business process instantiation. Unfortunately, we do not have an example that shows the whole process (SDI + BCM)"

"In future versions of the platform it is intented to introduce a group or company management, in order to be able to share capabilities with other people or companies."

Can we close this issue?

**Comment by diegoguidotti** [comment]
Dear Raul,
we still has not solved the issue to see a real working online example of
SDI (using our or other apps).

I started an issue a long time ago with no success:

https://bitbucket.org/fispace/apps/issue/95/sdi-test

then moved to

https://bitbucket.org/fispace/phase3support/issue/21/test-sdi-issue-95-bitbucket-apps

I am in contact with other projects and we are quite frustrated, in months
of request we was not able to se a woking example and a simple todo-list.

Best,
Diego

2015-06-02 12:27 GMT+02:00 Raul Palma notifications@github.com:

**Comment by rapw3k** [comment]
Dear Diego,

I am trying to catch up with your issues. 
As far as I understand the initial questions/problems related to this ticket have been solved: https://bitbucket.org/fispace/phase3support/issue/17/sdi-example 

Now you have started another ticket in bitbucket and the latest information is in https://bitbucket.org/fispace/phase3support/issue/21/test-sdi-issue-95-bitbucket-apps. It seems that it is still related to this ticket. 
The last entry in that ticket is you saying that you will create an application-config.xml file. Did you do that? what were the results? whats the status now?
Please provide feedback on what happened and I will push FIspace team harder to solve this issue.

**Comment by rapw3k** [comment]
Hi @diegoguidotti do you still have this issue? I did not receive your feedback yet. thanks

Update: tracking https://bitbucket.org/fispace/phase3support/issue/21/test-sdi-issue-95-bitbucket-apps.

**Comment by diegoguidotti** [comment]
Hi Raul,
I have uploaded the BCM file (I have added a message in the issue manage 4
days ago), and I have still a http 204 code. It is not clear if this is
correct, during my test someone told me that 204 is ok, other say that it
should return a 202 code.

In any case if I check my apache log I get no call.

Best,
Diego

2015-06-08 12:18 GMT+02:00 Raul Palma notifications@github.com:

**Comment by JanWillemKruize** [comment]
204 response means that FIspace was not able to handle the request synchronously. It is still processing the request and will send a resource available notification when finished. The resource available notification endpoint has to be configured as part of the business process.

The other possible result would be a 303, redirecting to the result of the request.

**Comment by diegoguidotti** [comment]
Thank you Jan. It is clearly a problem in BCM configuration, but its is really not clear how to setup it.

You can access my file in my repo: https://github.com/diegoguidotti/smartIPM/tree/master/sdi/bcb/Smart_Ipm

I have copied from the wc example but it is not clear how to define the notofiication endpoint.

Could you provide me an example?

Best,
Diego

**Comment by rapw3k** [comment]
Hi Diego,
Could you please let me know the status of this.
I see the bitbucket issue https://bitbucket.org/fispace/phase3support/issue/21/test-sdi-issue-95-bitbucket-apps on hold (I asked now  Zsuzanna about the new release).
Regards,
Raul

**Comment by diegoguidotti** [comment]
Hi Raul,
I have no idea on project developmnet, I am still waiting for some updates.

Best,
Diego

2015-07-03 16:19 GMT+02:00 Raul Palma notifications@github.com:

**Comment by perezdf** [comment]
trying to support you with real example, I have just finished some articles in

http://perezdf.bitbucket.org

Notice: Step by Step example within Examples

It is quite imminent the release of version 0.15.X of platform so, you can analysis the gap between 14 and 15 with the provided implementation.

Also you can use the deployed version in Integration Enviroment which I manage fully.

http://195.87.138.166:8080/sdi/

http://195.87.138.166:8088/wc-provider/

http://195.87.138.166:8089/app/
