### ISSUE TITLE
FISPACE authorization

### ISSUE THREAD

**Issue by rapw3k** [SAF2/documentation#13]
From David Castro:

We are developing client Authentication/authorization using Fispace and after our first oauth client tests we have some doubts about the authorization process. 
We have discover that in Developer zone we only are able to define Oauth clients with no posibilities to define user roles or assign resource access rules like Fiware GE:

Imágenes integradas 1Imágenes integradas 2

We assume that keycloack admin console is closed for third party app developers and we need to understand the next questions:
- Is there an admin console where manage application roles and resource authorization rules?
- SPT framework could be used for manage these permissions instead? How we can apply for SPT API access?
- If no one of the above requests is possible how a third party developer can manage their own roles using provided Fispace Oauth Manager?

**Comment by rapw3k** [comment]
More information will be available: https://bitbucket.org/fispace/phase3support/issue/16/fispace-authorization-doubts

**Comment by rapw3k** [comment]
Hi Emilio, 
I imagine you have seen the answer provided in bitbucket? In any case I copy it below.
Regards,
Raul

---

as you know, we are using keycloak as Idm server and we don't provide a role management for the applications out of the platform. - Is there an admin console where manage application roles and resource authorization rules? - SPT framework could be used for manage these permissions instead? How we can apply for SPT API access? We can't provide an admin console access or spt framework api for user role management.
If no one of the above requests is possible how a third party developer can manage their own roles using provided Fispace Oauth Manager? The Applications should implement their own role management if needed. We only provide platform roles 'user' and 'app_developer' to the apps. The other roles needed by application should be managed by the application.

**Comment by rapw3k** [comment]
Can we close this issue?

**Comment by vangelisv** [comment]
Hi Raul, this is not an issue I posted.

**Comment by rapw3k** [comment]
From Emilio (TerraLayer): This issue can be closed
