### ISSUE TITLE
Waterford Fi-Lab Node

### ISSUE THREAD

**Issue by kdempsey** [SAF2/documentation#14]
Hi, 
We would like to use the Waterford Fi-Lab node, could you please that this node is stable and can be used for our production servers? Is the plan for this node to stay up for the duration on the project?

Thanks, 
Kari

**Comment by kdempsey** [comment]
Hi, 

Could you also let me know what the different between these IP pools is please, and which we should be choosing: federation-ext-net-01 and public-ext-net-01. The option is given when selecting to assign a floating IP to the project. 

Thanks,
Kari

**Comment by rapw3k** [comment]
Hi Kari, 
I am checking on this. 
Regarding the second questions, is it general or for Waterford node?
Regards,
Raul

**Comment by rapw3k** [comment]
Hi Kari,
regarding IPs, federation is from private ip pool of xifi mdvpn (multi domain VPN) network and pubic are public ips
Raul

**Comment by rapw3k** [comment]
Hi Kari, 
also from Waterford team we received answer that:

"Yes - our uptime has been good in the past and aim to continue that for
as long as we can. We’re dealing with changes resulting from the IdM
upgrade. As with all production level services, I’d advise replicating
parts of your operations across a few availability zones/regions for
maximum uptime.”

**Comment by rapw3k** [comment]
if that answer your questions please close the issue.
thanks,
Raul

**Comment by kdempsey** [comment]
Thanks Raul, this can be closed.

Cheers,
Kari
