### ISSUE TITLE
"Unauthorized" error when uploading a widget to FISpace via Fispace studio

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#15]
We've set up the FiStudio as per the instructions on https://bitbucket.org/fispace/core/wiki/Configure%20specific%20repository%20with%20user%20and%20password%20in%20your%20local%20environment

When trying to upload a test widget on fispace we get:

[WARNING] Could not transfer metadata eu.fispace.apps:ifarma-ffa:1.0-SNAPSHOT/maven-metadata.xml from/to FIspaceApps (http://mordac.es.atos.net:8080/nexus/content/repositories/Fispace): Access denied to http://mordac.es.atos.net:8080/nexus/content/repositories/Fispace/eu/fispace/apps/ifarma-ffa/1.0-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 3.253s
    [INFO] Finished at: Fri Apr 24 16:59:07 EEST 2015
    [INFO] Final Memory: 64M/380M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy-file (default-cli) on project ifarma-ffa: Failed to retrieve remote metadata eu.fispace.apps:ifarma-ffa:1.0-SNAPSHOT/maven-metadata.xml: Could not transfer metadata eu.fispace.apps:ifarma-ffa:1.0-SNAPSHOT/maven-metadata.xml from/to FIspaceApps (http://mordac.es.atos.net:8080/nexus/content/repositories/Fispace): Access denied to http://mordac.es.atos.net:8080/nexus/content/repositories/Fispace/eu/fispace/apps/ifarma-ffa/1.0-SNAPSHOT/maven-metadata.xml. Error code 401, Unauthorized -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by JanWillemKruize** [comment]
Hi, do you still encounter this error?

**Comment by vangelisv** [comment]
Yes, nothing changed. Can you please verify that the connection information provided in https://bitbucket.org/fispace/core/wiki/Configure%20specific%20repository%20with%20user%20and%20password%20in%20your%20local%20environment
is correct?

**Comment by JanWillemKruize** [comment]
I am not sure. If you have connection issues maybe these connection details help:

https://bitbucket.org/fispace/core/wiki/Experimentation%20Environment

**Comment by JanWillemKruize** [comment]
To be able to help better we are working on a description how to create widgets and apps for FIspace. We hope to have this description ready at the end of next week.

**Comment by vangelisv** [comment]
Thank you. We're waiting for this description.
