### ISSUE TITLE
FiSpace studio issues

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#16]
Hi, we've downloaded the latest version of FiSpace studio v0.15.0-S1509 and we experience a lot of problems(?): 

1/ BCO Editor: Opens a web browser window, authenticate via keycloak then shows an empty page at http://37.131.251.135:8080/AcsiWeb...  Same empty page I get when trying to connect to http://37.131.251.135:8080/AcsiWeb directly via the browser.

2/ SDI Connector: When selecting this option FiStudio hangs (goes unrepsonsive)

3/ Capability Management. Doesn't seem to do anything. Querying (GETing) or PUTing something (Capability Types , Capabilities, Business processes, templates) does not return neither any registered object, nor any error or warning message.

Thanks for looking into this,
Kind regards,
Vangelis

**Comment by JanWillemKruize** [comment]
I will check it out. Maybe the documentation of this issue can help you a bit. 

https://bitbucket.org/fispace/phase3support/issue/17/sdi-example

**Comment by JanWillemKruize** [comment]
Hi, I posted your questions on: https://bitbucket.org/fispace/phase3support/issue/20/issues-with-the-fispace-ee 

It seems that the version v0.15.0-S1509 has not been released yet to the production environment. I think you can better use the older version.

**Comment by rapw3k** [comment]
@vangelisv, can we close this issue?

**Comment by vangelisv** [comment]
Yes we can close it.
I did not find yet solution to my problems but it does not help in anyway
keeping it open.

**Comment by rapw3k** [comment]
Did you try using an older version ?  Did you have the same or other problem?

**Comment by JanWillemKruize** [comment]
closed per issuers request
