### ISSUE TITLE
Problem creating Decoupled project on Linux

### ISSUE THREAD

**Issue by ralcaide** [SAF2/documentation#17]
Hi,

I'm trying to create a decoupled project with the wizard provided by the FIstudio but I'm getting the following error:

May 04, 2015 12:38:01 PM eu.fispace.plugin.wizards.handler.SetupWizard setupMavenSettings
INFO: SetupWizard.setupMavenSettings()
Done
May 04, 2015 12:38:01 PM eu.fispace.plugin.wizards.NewFispaceProjectWizard <init>
INFO: Starting .m2 settings
Creating APP WIDGET Archetype
NewFispaceProjectWizard.performFinish(REMOTE)
NewFispaceProjectWizard.performFinish(sCombo)Decoupled
May 04, 2015 12:38:18 PM eu.fispace.plugin.wizards.maven.MavenHandler generateMavenCall
INFO: Maven call generated
Maven call: archetype:generate-DarchetypeCatalog=http://37.131.251.110:8080/repository/-DarchetypeRepository=http://37.131.251.110:8080/repository/-DarchetypeGroupId=eu.fispace.apps-DarchetypeArtifactId=fispace-app-decoupled-archetype
May 04, 2015 12:38:18 PM eu.fispace.plugin.wizards.maven.MavenHandler execMavenTaskEmbeded
INFO: Executing maven
May 04, 2015 12:38:19 PM eu.fispace.plugin.wizards.maven.MavenHandler$1 run
INFO: executeMaven:result.1.0
May 04, 2015 12:38:20 PM eu.fispace.plugin.wizards.maven.MavenHandler$1 run
INFO: resultEE.2.0
org.eclipse.core.internal.resources.ResourceException()[567]: java.io.FileNotFoundException: /home/ralcaide/workspace/Decoupled3\backend.project (No such file or directory)

The /backend/.project exists but it seems there is a problem with the slash "\" instead of "/".

Do you know any solution or workaround for that?

**Comment by JanWillemKruize** [comment]
Hi, did you check these instructions: https://bitbucket.org/fispace/core/wiki/DevFaqCreateApp

**Comment by ralcaide** [comment]
Hi Jan,

thanks for this information. Executing the command on the bash works correctly. So, this is a great workaround
Anyway, creating the project from Eclipse+FIspace plugins doesn't work. 

If you think, this issue is resolved you can close it. My main problem creating a Decoupled project is resolved

**Comment by rapw3k** [comment]
@JanWillemKruize will you close this issue?

**Comment by JanWillemKruize** [comment]
workaround available, closing
