### ISSUE TITLE
Getting a community account for FiLab

### ISSUE THREAD

**Issue by kdempsey** [SAF2/documentation#2]
We would like to confirm what kind of account we have for the fiLab, the account is under kdempsey@togetheranalytics.com. There is a warning that if you use a trial account things will get deleted after 2 weeks, but we cannot find where we apply for the community account.

**Comment by rapw3k** [comment]
Dear Kari, our team is checking about this issue with technical people from FIWARE-lab. We will let you know as soon as we have some official answer.

**Comment by kdempsey** [comment]
Great thank you for getting back to me.

**Comment by rapw3k** [comment]
Dear Kari,
We have received information from FIWARE-lab support contact that it has been decided to postpone the migration for now. So (quoted from expert):
- You actually do not have an assigned user level (no one does at the moment), this will be done in a few weeks' time
- When we start the process, we will send another notification with more details and explanations on how to apply for higher categories
- The projects supported by the accelerators and also PPP initiatives will have right to a privileged access to FIWARE Lab, you should not worry too much 

---

Please if this solves your question, mark as solved this issue.

**Comment by rapw3k** [comment]
The new process has been notified via email. I am closing this issue
