### ISSUE TITLE
One-to-many collaboration in FIspace

### ISSUE THREAD

**Issue by beenotes** [SAF2/documentation#20]
In our application we want to achieve the following scenario:
A farmer wants to notify one or more beekeepers, who are in farmer's region.

As we already understood, in order to achieve this one-to-many collaboration through FIspace platform, we have to use the  Event Processing Module (EPM) functionality.
In order to use EPM the creation of capabilities and the corresponding rules is neccessary.
Where could I find more details about the definition of this kind of capabilities and rules?
Moreover, in which way the underlying implemented decision-making proccess from our backend information system will be connected to the EPM supported rules?

**Comment by JanWillemKruize** [comment]
Hi, I'm looking into this. It might be useful to have a skype call soon to discuss this issue.

**Comment by beenotes** [comment]
Sure, just let me know.

**Comment by JanWillemKruize** [comment]
shall we talk on skype this Wednesday? Can you sent me an e-mail then I will invite you on skype?

**Comment by rapw3k** [comment]
Can we close this issue?

**Comment by JanWillemKruize** [comment]
one-to-many collaboration is not related to event processing.

EPM:
- Any data producing device can be connected to FIspace using mqtt and the definition of a channel
- With EPM, a rule can be defined to trigger a business process when certain conditions in the data provided on the channels are met.

About one-to-many, basically the usage model of FIspace is the other way around. Companies can define what services they have to offer (capabilities) other companies can choose to make use of such a service (business process). This can range from simple (request-response) to complex (multiple chained services ultimately producing the response requested).

http://de.slideshare.net/FranciscoPrezDurn/business-capability-model-v10

FIspace does not support pushing data to one or more recipients.
