### ISSUE TITLE
Problem with keycloack authentication

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#23]
When our widget initializes keyclock (on keycloack.init) it gives the following error:
(debugged through firebug) 
_http://auth.ee.fispace.eu:8080/auth/realms/fispace/protocol/openid-connect/login-status-iframe.html?client_id=ifarma&origin=http://37.131.251.130:8088   Error 404, Not Found_ 

We've defined our oath client in FISPACE App developer zone, and used the keycloack.json file in building the widget.

Any idea what might be wrong?

**Comment by rapw3k** [comment]
Moved to FIspace team: https://bitbucket.org/fispace/phase3support/issue/32/keycloack-authentication-issue

**Comment by rapw3k** [comment]
Please also read previous similar issues: https://bitbucket.org/fispace/phase3support/issue/11/fispace-authentication and https://bitbucket.org/fispace/phase3support/issue/16/fispace-authorization-doubts

**Comment by rapw3k** [comment]
Hi @vangelisv can you let me know the status of this issue? From the issue in Bitbucket, I understand there was an update, but didn't get your feedback?
thanks,
Raul

**Comment by vangelisv** [comment]
Hi, 

No! There is no progress/nor any solution to this issue. The same problem is very well analyzed in phase3 support issue #24 (by David Castro).  Open-id connect authentication is not working in FISpace keycloak instance.

**Comment by rapw3k** [comment]
Hi @vangelisv please find reply in bitbucket and provide the information required. thanks - https://bitbucket.org/fispace/phase3support/issues/32/keycloack-authentication-issue

**Comment by vangelisv** [comment]
The issue is now resolved. Moving forward with keycloak integration we now face the issue #46
