### ISSUE TITLE
Web ACSI Editor 'looses' Business Entities.

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#24]
a) Connected to ACSI Editor (http://37.131.251.156:8080/AcsiWeb/AcsiEditor.html) credentials fispaceUser/fispaceUser

b) Created two new applications ifarma-ffa and ifarma-ffa2. (Each time I click on any of the new apps I get a messagebox with a warning with an empty text).

c) Created a new Business Entity "Farm" on both but now I'm not able to see/access it on the object browser in the left.  

d) If a try to create again the BE with the same name in ffa2, I receive message "["Error: Request application 'ifarma_ffa2' does not exists"]. 
Similarly, in ifarma-ffa, I receive the message 
["Error: Component Farm in application ifarma-ffa for user fispaceUser already exists"]

Thanks for looking,
Regards,
Vangelis

**Comment by rapw3k** [comment]
Hi Vangelis, 
I have forwarded your issue to Fispace team: https://bitbucket.org/fispace/phase3support/issue/27/acsi-editor-issues-from-sme

In the meantime please take a look at similar issues:
https://bitbucket.org/fispace/core/issue/1298/acsi-editor-is-not-shown-in-the-internal
https://bitbucket.org/fispace/core/issue/1237/exception-generated-from-acsi-editor

**Comment by vangelisv** [comment]
It appears that the problem was the dash (-) in the app name. I created another app named ifarma_ffa and now it works....
