### ISSUE TITLE
AcsiEditor (BizArtifact)

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#25]
We try to figure out how to work with the ACSI editor tool in order to create our B2B workflow. We use the tool's User Manual guide to understand how it works. 

In order to better understand the runtime engine of the tool and how you can use it for testing is it possible to have a "download" of the example used in the Manual (HelloWorld App with the HelloArtifact)?

**Comment by rapw3k** [comment]
Keep track of: https://bitbucket.org/fispace/phase3support/issue/33/acsi-editor-bizartifact

**Comment by rapw3k** [comment]
@vangelisv as you have probably seen in bitbucket, the only available published example (note it also appears in some of the screenshots) is [this one](http://sourceforge.net/p/bizartifact/code/HEAD/tree/trunk/doc/OrderToCash.zip)

Can we close this issue?
