### ISSUE TITLE
Creating an BusinessProcessTemplate in ACSI (BCM Authoring tool)

### ISSUE THREAD

**Issue by ralcaide** [SAF2/documentation#26]
Hello,

after the Capabilities and B2B Webinar from yesterday and the new documentation (https://bitbucket.org/fi-space/doc/wiki/Guide%20for%20BCM%20v0.1) we are trying to create a BusinessProcessTemplate (ACSI app). It is possible to see our App (SmartLight) in the ACSI Tool.

We developed something but the documentation is still unclear and too complicated for us. 
We have several concrete questions:
- How to fill ca:Event entry in the XML one would add a field such as: <ca:CorrelationKey id="<SomeId>" artifactType="<BusinessEntityName>"> <ca:KeyAttribute id="KeyAttribute1" eventXpath="/<EventType>InputMessage/businessProcessId[1]" artifactXpath="/<BusinessEntityName>/businessProcessId" operator="="/> /ca:CorrelationKey ?
  What is the CorrelationKey id?
- How can we configure the bridge?, where is the bridge?. The phrase  "The bridge configuration also needs to be set-up; this is primarily done in the application-config.xml file." is in the new doc but what is the concrete meaning of that?
- How can we configure a Marshaller? 
- The zip with the ACSI App should be uploaded to CBBridge page. Which page?  URL?

For us, the documentation is really really complicated. It is not possible to create a concrete step by step example?. Maybe a video like an screencast?.

**Comment by ralcaide** [comment]
Hello,

any news about that?

**Comment by rapw3k** [comment]
Hi,
We have contacted FISpace team: https://bitbucket.org/fispace/phase3support/issue/34/creating-an-businessprocesstemplate-in
We will be tracking it

**Comment by gitoni** [comment]
Hi,
we are waiting for an answer to this ticket aswell.

Thanks

**Comment by rapw3k** [comment]
Hi @gitoni please see answer in https://bitbucket.org/fispace/phase3support/issue/34/creating-an-businessprocesstemplate-in 
Does that solve your issue?

**Comment by gitoni** [comment]
Hi,
sorry for the late answer.
I prepared the SDI capabilities/capbility types and business processes / templates. Also I created ACSI-GSM models. But I am still not able to connect between the ACSI-GSM and the FISPACE SDI even that I read through the Business Architect Guide. I think there is also no comprehensible example showing how this can be done. 
What is the advise from SmartAgriFood to Phase 3 projects regarding the promise that the BCM will be userfriendly in the future. Is it okay to wait for these functionalities and that we focus more on  developing functionalities of the frontend widget for the FISPACE Wirecloud at the moment?

**Comment by ralcaide** [comment]
Hi, why is this issue close? : https://bitbucket.org/fispace/phase3support/issue/34/creating-an-businessprocesstemplate-in

For me, this issue is not solved. I don't know if for @gitoni is solved.

**Comment by gitoni** [comment]
Hi, no it is not solved for me. I would need to see step by step example screencast, which would show the most simple use case using a super basic ACSI-GSM and FISPACE SDI-BusinessProcess together. E.g. receive an event, process task, send notification, receive notification.

**Comment by ralcaide** [comment]
Yes, I would need to see the same example.

**Comment by rapw3k** [comment]
The issue is open (waiting for some help), but if you have any further feedback would be welcome.
See https://bitbucket.org/fispace/phase3support/issue/34/creating-an-businessprocesstemplate-in

**Comment by gitoni** [comment]
Thank you, I would be ready to give more feedback to help creating that step by step example.

**Comment by sbrahma** [comment]
Hello @ralcaide , 
Its just to inquire about the present status of this issue from your side. We are planning to close these issues if they are being resolved somehow.

Thanks

**Comment by ralcaide** [comment]
Hello,

yes, you can close this issue
