### ISSUE TITLE
FIspace core wiki is not anymore accessible

### ISSUE THREAD

**Issue by ralcaide** [SAF2/documentation#28]
Hello,

I was using documentation from the wiki of the core team that was accessible until now. At this moment, it is not accessible because the rights are changed (i.e: https://bitbucket.org/fispace/core/wiki/FrontEnd/HowToCreateOAuthClient)

It is normal? Is this documentation accessible using another link?

**Comment by ralcaide** [comment]
Hi, 

I've found an faster way to find the answer to my question. Yes, the core wiki is now closed. We can access to this information here: https://bitbucket.org/fi-space/doc/wiki/gui/HowToCreateOAuthClient

The SAF2 team can close the issue

**Comment by rapw3k** [comment]
Thank you for the update @ralcaide 
Regards
