### ISSUE TITLE
Request for a step by step guide

### ISSUE THREAD

**Issue by irafa** [SAF2/documentation#29]
Hello,

We are trying to develop an application that would use some capabilities of Fispace platform and we pretend to publish a capability in order to provide to the platform the data with which we are working.

We have created a "Decoupled" proyect in Fistudio but we dont know how to proceed in order to modify this decoupled project or how to modify the existing examples of projects that are in the App section of bitbuckler (https://bitbucket.org/fispace/apps/src) in order to develop our application.

We are trying to use a capabilty that provides forecast weather in order to show this information together with the data from our application, in a widget.

We would like to know if you can provide some development guide that shows up a step by step procedure to follow.

Thanks in Advance,
Rafa.

**Comment by sbrahma** [comment]
hi
Your proposal has been forwarded to FISPACE in 
https://bitbucket.org/fispace/phase3support/issue/53/request-for-a-step-by-step-guide

**Comment by sbrahma** [comment]
Hello @irafa ,

 please follow the latest activity on this issue in bitbucket and let us know that if its ok to close the issue or not.

Thanks.

**Comment by irafa** [comment]
Hello,

Yes, the information provided for Francisco has been usefull and we are
moving forward.

Thanks,
Rafa

2015-07-13 10:30 GMT+02:00 Soumya Brahma notifications@github.com:

**Comment by sbrahma** [comment]
thanks @irafa , So this issue i can close?

**Comment by irafa** [comment]
Yes, thanks for your attention,

Regards,
Rafa.

2015-07-13 10:51 GMT+02:00 Soumya Brahma notifications@github.com:
