### ISSUE TITLE
server space and IP's

### ISSUE THREAD

**Issue by kdempsey** [SAF2/documentation#3]
We would like to request another 3 external IPs, we only have one at the moment which we will use for our web app but also want to have a dev, test and prod environments which all need to accessible externally and we would like to host our bug tracking server on one if possible so that is 4 in total, therefore we would like a 5 server allowance if possible please and a larger memory allocation etc.. In the previous email response from the tech people it said we could request more. 

Also, are there any Ubuntu (13.04 or later) images which have more than 3.5GB ram? We would like more if possible + 8GB, I can see other that have 10GB but these are not the base Ubuntu images. 

Many thanks,

**Comment by Astagor** [comment]
Hi,

I have been talking with the FIWARE people and the answer is: when the Community accounts will be in place, each of the A16 accelerators (including of course SAF2) will have specific FIWARE nodes assigned to support the SMEs. Then your request can be sent to such a node and they will try to provide you the resources you need.

BR,

Piotr

**Comment by rapw3k** [comment]
Dear Kari,

Can you tell us the name of the region you use ?

Regards,
Raul

**Comment by kdempsey** [comment]
Hi,

I am using the Spain region. I am in the UK and was advised to use the
Spain one.

Best regards,
Kari

**Comment by kdempsey** [comment]
Hi, 

Is there any update on this please, we would like to know we have a stable setup before doing too much dev. 

We also need more external IPs asap..

Regards, 
Kari

**Comment by SPvanG** [comment]
Hi, I have a related issue.
I'm having trouble assigning a public IP to a virtual machine. I've tried multiple regions but can't find any that has any public IPs available. Is there any public IP left anywhere?

**Comment by rapw3k** [comment]
Hi Kari,
We are still waiting more detailed response from Spain node helpdesk (yesterday your request was resubmitted). I will let you know as soon a we have their feedback. However also note, as mentioned in https://github.com/SAF2/documentation/issues/2, there are no assigned user levels yet (you will be notified when the community level will launch. However, the projects supported by the accelerators and also PPP initiatives will have right to a privileged access to FIWARE Lab, you should not worry too much.
Regards,
Raul

**Comment by rapw3k** [comment]
Hi SPvanG,
We will check about this and get some feedback.
Regards,
Raul

**Comment by rapw3k** [comment]
Hi SPvanG,
We have not receive general answer, but at least from one of the nodes we received the following information:
"our node (PiraeusU Node) has available public IPs. Please advise the user to use "public-ext-net-1" in order to assign a floating IP to his virtual machine."
Regards,
Raul

**Comment by SPvanG** [comment]
Thank you Raul, I will give it try at the PiraeusU Node.

**Comment by SPvanG** [comment]
Hi Raul, thanks for your help earlier! 
I was able to get a public IP on the PireasN Node, but I can't reach, not even ping, my VM on the public IP that I assigned to it. Any ideas on why this may be the case?

**Comment by rapw3k** [comment]
please give us some details of the VM (location, Ip, ) so we can ask correct node helpdesk.

**Comment by kdempsey** [comment]
Hi Raul, 

We are still waiting to hear on getting external IPs and extra server allocation. We are trying to get new external IPs on either Poznan or Spain, but we don't mind where we just need some! 

Please could you give us an update, this is now holding up our dev. 
Many thanks,
Kari
Grocircle

**Comment by SPvanG** [comment]
Hi Raul, here are some details:

IP Addresses: node-int-net-01: 10.60.4.76 / node-int-net-01: 185.23.171.28
name: connecterra_vm
Floating IP Pool: public-ext-net-01 
Image Name:  Ubuntu12.04-server-x86_64 
Region: PiraesN
Security Group: default
Status: ACTIVE
Power State: RUNNING

The Instance Console Log is Empty

**Comment by rapw3k** [comment]
Hi @kdempsey,
I did not reply earlier as I was waiting feebdack from the infrastructure people in Poznan and in Spain. Regarding Poznan (our node), we can only offer at the moment 4GB VMs, this will improve of course later but at the moment this is a constraint. Regarding IPs we dont have problem to assign multiple public IPs. 
Regarding Spain node, even though I have been insisting twice again this week, I did not receive any feedback I am afraid they may be on holidays. I think if you would like to keep using Spain, I will have to put you in direct contact with them, as there is no more we can do here... 

Please let me know what would you like to do...

**Comment by kdempsey** [comment]
Hi Raul, 
That's great, we are happy to use the Poznan one, we would like 4GB Ubuntu 14.04 servers then. Could we please have a server allowance of 5 servers on the Poznan node then and please have 3 external IPs? At the moment I don't have any external IPs on the Poznan one. 
Thanks for your help!
Kari

**Comment by kdempsey** [comment]
Hi Raul, 

We are still waiting for the external IPs ? We need these asap please, we still only have the same server allowance as well. My user is kdempsey@togetheranalytics.com

This is holding up our project.

Regards, 
Kari

**Comment by rapw3k** [comment]
The issue with Kari has been solved with Poznan node. 
Can we close this issue?

**Comment by kdempsey** [comment]
Hi Raul,

Yes thanks please close.
