### ISSUE TITLE
Problems to contact with the developers group of two applications.

### ISSUE THREAD

**Issue by irafa** [SAF2/documentation#30]
Hello,

We are working on a project which is related to monitoring greenhouses. We proposed to develop an application which interacts with others two apps that are described in Fispace platform as part of "Greenhouse management and control" section.

These applications are:

Greenhouse Monitoring & Advice:
http://fispace.eu/greenhouse-crop-monitoring-advice.html

Greenhouse Crop Monitoring:
http://fispace.eu/greenhouse-crop-monitoring.html

We tried to contact several people from these app developer groups but we did not success. We would like to know if these applications have an API or are available in Fispace in order to communicate with it. 

We do not know whether these applications are only a user application or not. Do they have a development usage in order to enable developers to make applications which interact with their applications?

Could you advise us about the communication with these developers groups?

Thanks,
Rafa.

**Comment by JanWillemKruize** [comment]
I asked the developers. Regarding the greenhouse monitoring & advice app , it was developed by the Univiersity of Athens and it has been used in the greenhouse trial but doesn't provide any accessible API. It only fits the needs of one user regarding the greenhouse advice scenario, by connecting to an FMIS and getting sensor values. It is not accessible by other  applications.

With regards to Greenhouse crop monitoring app, it is developed by Mobics company. You can try to contact them based on the information in the app page:
http://fispace.eu/greenhouse-crop-monitoring.html however, I guess you have tried this already...

**Comment by irafa** [comment]
Hello Jan,

Yes, we tried to contact them through all the emails but we had no success. We do not know if we should try others ways or that is the only way we have.

Thanks for the information about"Greenhouse Monitoring & Advice" app; it is useful for us in order to decide what to do in Fispace.

Thanks,
Rafa.
