### ISSUE TITLE
[FISPACE] Administration of company profile

### ISSUE THREAD

**Issue by gitoni** [SAF2/documentation#33]
While filling the company profile on the FISPACE EE platform we encountered a few shortcomings, which we would like to let you know for further improvements. It seems that the administration of a company profile is still a bit incomplete. E.g.
- it is not possible to administrate employees,
- an employee can't be assigned as administrator to edit the company profile,
- eyeryone can join any company.
- it is not possible to delete a logo or cover image
- if the uploaded logo was not in a squared like dimension, it can't be changed. This is because the button is not accessible anymore. The "upload" button appears when mouse over the logo, but disappears as soon as you move the mouse to click on it.

Best regards,
Toni

**Comment by sbrahma** [comment]
your issue has been forwarded to the FISpace team.
https://bitbucket.org/fispace/phase3support/issue/45/fispace-administration-of-company-profile

**Comment by sbrahma** [comment]
Please see the answer in https://bitbucket.org/fispace/phase3support/issue/45/fispace-administration-of-company-profile

**Comment by gitoni** [comment]
Thanks sbrahma for forwarding. Looking forward for the new releases.

> - It is not possible to delete a logo or cover image
> 
> Could you detail me what do you mean with "delete"? Disable it completely?`

It was just a little bit confusing, but as long as you can change it by uploading a new one, it is actually not really an issue..
