### ISSUE TITLE
[FISPACE Store] Only one screenshot is shown

### ISSUE THREAD

**Issue by gitoni** [SAF2/documentation#35]
We have published a widget/application in the FISPACE EE store and added 3 screenshots.
Though only the last one is shown and the "next" and "previous" buttons for the screenshot slideshow don't react.

**Comment by sbrahma** [comment]
Hello @gitoni 
Please follow your query in the FISPACE in :
https://bitbucket.org/fispace/phase3support/issue/48/fispace-store-only-one-screenshot-is-shown

**Comment by sbrahma** [comment]
Hello,
There has been a new version of WStore released in 24.07.2015. Please implement this and check if this version suits your requirements. I think the rest is answered in the thread of FISPACE team.

**Comment by sbrahma** [comment]
Hello @gitoni , 
Its just to inquire about the present status of this issue from your side. We are planning to close these issues if they are being resolved somehow.

Thanks

**Comment by gitoni** [comment]
Hi sbrahma,
we have got an answer from the FIspace team and the issue has been closed.
This ticket can be closed too.
Than you
