### ISSUE TITLE
[FISPACE Store - feature request] Temporarly disable offer

### ISSUE THREAD

**Issue by gitoni** [SAF2/documentation#36]
Once an offer is published in the store it can be deleted, but it is not possible to make it private and later make it public again, i.e. disabling the offer temporarly. That would be a necessary functionality.

**Comment by sbrahma** [comment]
Hello @gitoni your proposal has been forwarded to the FISPACE team followed in https://bitbucket.org/fispace/phase3support/issue/47/fispace-store-feature-request-temporarly

Thanks

**Comment by sbrahma** [comment]
Hello @gitoni , there has been a recent update of the Wstore GE, please confirm us that if the new version meets your requirement. If something is still missing we will directly contact the GE developers. In case you have more quires you can contact the person responsible. Contact details are as below:
Francisco de la Vega
Email: fdelavega@fi.upm.es 
Address: School of Computer Science 
Universidad Politécnica de Madrid Campus de Montegancedo 
s/n 28660 Boadilla del Monte, Madrid (Spain)

Thank you
