### ISSUE TITLE
[FISPACE Store] How to create a widget, data or service offer?

### ISSUE THREAD

**Issue by gitoni** [SAF2/documentation#37]
When creating an offer in the FISPACE store you can fill a content type, but it is not clear for me how to classify the type, so that the offer is listed as widget (or service/data) in the store.

**Comment by sbrahma** [comment]
Hello @gitoni 
Your question is forwarded to FISpace team in https://bitbucket.org/fispace/phase3support/issue/46/fispace-store-how-to-create-a-widget-data

Thanks

**Comment by sbrahma** [comment]
Hello @gitoni 
Does the answer in bitbucket resolve your issue?

**Comment by gitoni** [comment]
Hi sbrahma,
yes , thanks for the clarification. 
I will try to use the SDK too.

The issue can be closed.
