### ISSUE TITLE
FiSpace issue with Create Business Process

### ISSUE THREAD

**Issue by kdempsey** [SAF2/documentation#38]
Hi Raul, 

I have FiSpace studio installed and have uploaded a dummy widget for testing. I have been trying to create a new business process in FiSpace for use in our web service for GroCircle. On the page for setting up the Business & Capabilities I have created the capability green house advice, that seemed to work ok. When I try to create the business process it will not let me select a capability. I have reviewed the documentation and the open issues in bitbucket but it is not clear what the issue is. Could you please offer some advice or forward the query on? 

Many thanks, 
Kari

**Comment by sbrahma** [comment]
your issue has been forwarded to the FISPACE team.
https://bitbucket.org/fispace/phase3support/issue/52/fispace-issue-with-create-business-process

**Comment by kdempsey** [comment]
Still no feedback on this issue in bitbucket? Can you chase? Thanks, Kari

**Comment by perezdf** [comment]
it is a bug in the form, the bottom combo doesnt refresh. If you refresh the page (F5), the recently created cap is offered in this combo

**Comment by sbrahma** [comment]
Hope this will solve your problem Kari.
