### ISSUE TITLE
Issue creating FiSpace New KeycloaK OAuth Client

### ISSUE THREAD

**Issue by kdempsey** [SAF2/documentation#39]
Hi Raul, 

I am getting an error when creating a New KeycloaK OAuth Client in the developer zone for FiSpace. I enter the values similar to those in the page https://bitbucket.org/fi-space/doc/wiki/gui/HowToCreateOAuthClient but I get an error saying "may not be empty", all the text boxes have values so I am not clear on the issue. Could you please refer the query? 
Many thanks, 
Kari

**Comment by sbrahma** [comment]
hi Kari, 
Your issue has been forwarded to FISPACE team at
https://bitbucket.org/fispace/phase3support/issue/51/issue-creating-fispace-new-keycloak-oauth

**Comment by sbrahma** [comment]
Hello Kari, 
The response from FISPACE team is https://bitbucket.org/fispace/phase3support/issue/51/issue-creating-fispace-new-keycloak-oauth.

Regards.

**Comment by sbrahma** [comment]
Hello Kari,
The responses in the bitbucket is proving to be any solution for you?

regards

**Comment by kdempsey** [comment]
Hi, 
The original issue is resolved, I have a raised a further query on the same thread as the documentation is unclear. Thanks, Kari

**Comment by sbrahma** [comment]
Hello @kdempsey , so i am closing this issue as you are following a different query in the thread in FISPACE support.
