### ISSUE TITLE
Access to the FIspace SDI

### ISSUE THREAD

**Issue by gitoni** [SAF2/documentation#4]
Hi SAF tech team,

I would like to access the FIspace SDI.

However the API links from the docs don't work:
http://37.131.251.57:8080/fispace/api/capabilities 

http://37.131.251.117:8080/fispace/api/capabilities also doesn't work...
Does the experimental environment offer the SDI api? 
What would be the correct URL request?

Best regards,

Toni

**Comment by rapw3k** [comment]
Hi Toni,
please also see https://github.com/SAF2/documentation/issues/6 
Regards,
Raul

**Comment by gitoni** [comment]
Thank you! 
From the answer in  [#6](https://github.com/SAF2/documentation/issues/6#issuecomment-84876744) the correct links can be found here:
https://bitbucket.org/fispace/core/wiki/Experimentation%20Environment

i.e. to request a capability object:
http://37.131.251.117:8080/sdi/api/capabilities/1
