### ISSUE TITLE
Wstore not working in FISpace?

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#41]
'm trying to access Store in Fispace EE. When clicking on the store icon (menu to the left) I get the GE Store screen but empty. (See attached image) 
I
![wstore](https://cloud.githubusercontent.com/assets/51535/8477394/69adb1bc-20d2-11e5-9f9a-243aa1d53251.png)
We cannot do anything in the Wstore GE Any idea what is wrong?

**Comment by sbrahma** [comment]
The issue has ben forwarded to the FISpace Team in https://bitbucket.org/fispace/phase3support/issue/54/fispace-store-wstore-not-working-in

**Comment by sbrahma** [comment]
Dear @vangelisv please refer to the issue forwarded to FISPACE support from the above mentioned address and let us know if their reply helped you after all.

Thanks.

**Comment by vangelisv** [comment]
Hi,
the reply says that the complete store functionalities have not been implemented in the EE yet and it will take time. 
It does help from a "good to know" point of view, but it does not help us at all in planning our work and implementing our project.

**Comment by vangelisv** [comment]
We, still, can not access WStore from the EE. Same issue as #41.
Clicking on the "store" icon in the left side bar of EE, we get an empty Store screen. The firefox debugger reports:

```
"NetworkError: 404 NOT FOUND - http://37.131.251.130:8000/api/administration/profiles/v.vassiliadis@agrostis.gr"
```

It seems Fispace EE or keycloak does not provide a "correct profile" to the Wstore. In Wstore account settings we are not able to edit anything. Settings popup is displayed but neither profile info or tax address is editable.

**Comment by sbrahma** [comment]
Hello i have created a new issue in continuation of this issue. Please follow it in bitbucket at 

https://bitbucket.org/fispace/phase3support/issues/61/fispace-store-can-not-access-wstore-from

Thanks

**Comment by perezdf** [comment]
after a quick check, there are two topics, issue #41 referes to a login, basically the http://37.131.251.130:8000, second the specific connection to http://37.131.251.130:8000/api/administration/profiles/

for the first topic, I was able to login with firefox, so maybe is the version or the user. let's work on first topic, before reaching second, can you try with user sditestappdev/sditestappdev1234?

let me know what happens?

**Comment by vangelisv** [comment]
Hi,

yes it works with user sdi... So it is a problem with the specific user v.vassiliadis@agrostis.gr
Both issues refer to same problem.
I was also able to access store by registering another user for my company/organization.
Issue closed
