### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#42]
Is there any MarketPlace installed / available for FISpace EE? If yes, what is the URI we should type in "Add MarketPlace"

**Comment by sbrahma** [comment]
Hi, 
Your issue has been posted to FISPACE team at https://bitbucket.org/fispace/phase3support/issue/55/marketplace

Thanks.

**Comment by sbrahma** [comment]
Hello,
Probably you have seen the reply for your issue in bitbucket. So after this can i close this issue?

Regards.

**Comment by vangelisv** [comment]
Hi, 

the reply says that Marketplace has a long standing bug and is not available in FiSpace EE. 
Please close the issue.
