### ISSUE TITLE
Clarification on FiLab servers

### ISSUE THREAD

**Issue by kdempsey** [SAF2/documentation#44]
Hi, Could I please have some clarification on the status of our FiLab servers - there is a problem with our admin page. 
When I login to the https://cloud.lab.fiware.org/#nova I can see Spain2 and Prague but not Poznan - we should have Spain2 and Poznan. We still have servers running on Poznan as I can access them via ssh but I cannot see the Poznan ndoe through the admin screen. 
We should have 2 external IPs for the same node but we only have one each for Spain2 and Prague. 
My tenant ip is 00000000000000000000000000004383, login name kari cloud. 

Please clarify: 
-which nodes we should have?
-why we cannot see our existing servers in Poznan?
-why we do not have 2 external IPs on each node?
-will we lose our existing servers on Poznan? (we already have them setup so hopefully not.)

Thanks, Kari

**Comment by rapw3k** [comment]
Hi Kari, we will check about this.

**Comment by kdempsey** [comment]
Great thanks Raul,

**Comment by rapw3k** [comment]
Can we close the issue?

**Comment by kdempsey** [comment]
Yes please close,  thanks
