### ISSUE TITLE
Bad Gateway while creating offering in store (in EE)

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#47]
I try to create a new offering in store (user ffa@agrostis.gr). 
I enter all required info and at the end I get a Bad Gateway message:

![screen shot 2015-08-05 at 1 39 10 pm](https://cloud.githubusercontent.com/assets/51535/9083988/918a351a-3b77-11e5-9561-0199710bbb12.png)

**Comment by sbrahma** [comment]
Please follow it in FISPACE at 

https://bitbucket.org/fispace/phase3support/issues/62/fispace-store-bad-gateway-while-creating

Thanks

**Comment by sbrahma** [comment]
Hello, 
Its just to inquire about the present status of this issue from your side @vangelisv  . We are planning to close these issues if they are being resolved somehow.

Thanks

**Comment by vangelisv** [comment]
Hi, 
we have no resolution or feedback about this issue.
Also we've tried to workaround by creating the Store offering via the FIspace SDK and we also faced another problem that is in https://bitbucket.org/fispace/phase3support/issues/66/unable-to-upload-a-widget-to-the-store

So I would say that this current issue is related the the phase3support issue number 66

**Comment by sbrahma** [comment]
Hello @vangelisv 
So if this issue matches with  the issue #66 in bitbucket, is it ok if i  close this issue?

Thanks

**Comment by vangelisv** [comment]
Yes, we can close this issue.
