### ISSUE TITLE
Keyrock issue

### ISSUE THREAD

**Issue by PanonitMilos** [SAF2/documentation#48]
We are developing an Android application and want to authenticate our users based on the keyrock instance from the Fiwarelab (temporarily before installing our own Keyrock instance on our server).
So we have imagined this being exactly like google or facebook sign in. We want to use the public and private keys provided while registering the app.
The method (out the only two available) we have chosen is "Resource Owner Password Credentials Grant."

In our test authentication method we only created a simple code to check for username and pass. But we wish to use the esource Owner Password Credentials Grant that keyrock allows to use.

```
public void enter(View view){
 onButtonClicked.start();
//     if(cultureName == "Select culture")
//     {
//      Toast.makeText(this, "Please select culture!",Toast.LENGTH_SHORT).show();
//     }
//     else if(cultureName == null)
//     {
//      Toast.makeText(this, "Please check your internet connection!",Toast.LENGTH_SHORT).show();
//     }
//     else
 EditText user = (EditText)findViewById(R.id.editText1);
 username = user.getText().toString();
 EditText pass = (EditText)findViewById(R.id.editText2);
 password = pass.getText().toString();
 //if(username.equals("ad") && password.equals("ad"))
 {

      Intent intent = new Intent(this,MainActivity.class);
      startActivity(intent);
      IntroActivity.this.finish();
 }
 //else
 {
  //Toast.makeText(getApplicationContext(),"Username or password are incorrect! Please try again!", Toast.LENGTH_LONG).show();
 }

}
```

Any kind of help, examples, hello world, would be more than welecome. Thank you!

**Comment by sbrahma** [comment]
Hello, your issue has been forwarded to the FIWARE Q&A:

https://ask.fiware.org/question/63/keyrock-issue/

Thank you.

**Comment by sbrahma** [comment]
Hello, 
Its just to inquire about the present status of this issue from your side @PanonitMilos  . We are planning to close these issues if they are being resolved somehow by now.

Thanks
