### ISSUE TITLE
Comos database privacy

### ISSUE THREAD

**Issue by mrjfip** [SAF2/documentation#49]
We have registered to Comos server.
The user name allows to upload files.
For database operation there is no need for further authentication.
We can reach database and tables of any users. We noticed update to our table from outside.

So is Comos an open data processing environment? Or is it a malfunction?

Added a screenshot of the php code

![data_insert_code](https://cloud.githubusercontent.com/assets/13782883/9252490/dfe93992-41d8-11e5-9853-1bd9c6f0aaa3.png)

**Comment by sbrahma** [comment]
hello, i have posted your query in the FIWARE Q&A : 

https://ask.fiware.org/question/79/cosmos-database-privacy/

**Comment by mrjfip** [comment]
As the answer in the quoted FIWARE Q&A entry suggest the problem is fixed by now. However, it seems like other issues arisen related to the solution, namely:

Through ssh connection, the typing the hive command results in the following error: 

![cosmos_ssh_hive_error](https://cloud.githubusercontent.com/assets/13782883/9439517/0d24350a-4a68-11e5-9a46-9d8a24e016d4.png)

the hiveSQL queries work fine (through ssh) regardless the error message.

When launching exactly the same hiveSQL queries (each one of them worked flawlessly
two weeks ago) remotely, the request times out even in absurd time windows (10 minutes). 
The most basic commands ('use $username;', 'show tables';) also time out.

(The thrift client is: https://github.com/garamon/php-thrift-hive-client )

Since the Cosmos usage is an integral part of our project, it is of utmost importance whether
it is a temporal issue caused by the fixes or it is a permanent change in the remote availability
(could not identify relevant changes in the documentation).

**Comment by sbrahma** [comment]
Please follow it here:
https://ask.fiware.org/question/84/comos-database-privacy-2/

**Comment by sbrahma** [comment]
Hello, 
Its just to inquire about the present status of this issue from your side @mrjfip . We are planning to close these issues if they are being resolved somehow. 

Thanks

**Comment by mrjfip** [comment]
```
Hello!

  The issue is solved

  Thanks
  Máriás József
```

mob. +36-30-9473248
jmarias@loginet.hu

```
  2015.09.30. 10:40 keltezéssel, Soumya Brahma írta:


  Hello, 
    Its just to inquire about the present status of this issue from
    your side @mrjfip
    . We are planning to close these issues if they are being
    resolved somehow. 
  Thanks
  —
    Reply to this email directly or view
      it on GitHub.
```
