### ISSUE TITLE
FISpace SDK Plugins not available for Eclipse for MacOS?

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#5]
Hi,

following the instructions on the Annex FISpace SDK User-Developer Guide, we downloaded a new version of Eclipse (Luna) on an Apple MBP.
We also installed the FISpace plugins using the FISpace update page. Installation completed successfully but when restarting Eclipse no FISpace icon on the toolbar not any menu item for the FISpace plugins is displayed.

Regards,
Vangelis

**Comment by JanWillemKruize** [comment]
Dear Vangelisv,

At this moment we do not have an answer. I have forwarded your question to the FIspace team and hope to receive a answer soon.

Best regards,

Jan Willem

**Comment by GIPdA** [comment]
Hi,

I had the same problem (checking the Error Log (Window > Show View) in Eclipse helped a bit).
You probably don't have Java SE 1.8 SDK installed, FIspace needs 1.8.
May be necessary to set JAVA_HOME to 1.8 : export JAVA_HOME=/usr/libexec/java_home -v 1.8

Best regards,
Benj

**Comment by JanWillemKruize** [comment]
Hi Benj, 

Thanks for your respons. Vangelisv is your problem solved now?

Best regards,

Jan Willem

**Comment by vangelisv** [comment]
I'll check with Java SE 1.8 and come back to you. Thanks!

**Comment by vangelisv** [comment]
Problem is solved!. Many Thanks.
