### ISSUE TITLE
FIspace Platform

### ISSUE THREAD

**Issue by JanWillemKruize** [SAF2/documentation#6]
Can I ask you some question about the application development with the FIspace platform? 

I am trying to work with the eclipse FIspace Studio SDK. 
1. When accessing the Event Processing Module (EOM Proton) the page keeps reloading every second. This makes it impossible to work with the module. 
1. Accessing the Business Collaboration Module fails. The answer I get is: bad request, resource not found.   
2. Connecting to the SDI api does not work too. Which URL do I have to use? 

Do you know a solution for these three problems? 

Thank you very much and best regards, 

Toni

**Comment by JanWillemKruize** [comment]
Hi Toni,

I have not an answer at this moment. I will send your questions to the FIspace team and hope to receive a response soon!

Best regards,

Jan Willem

**Comment by gitoni** [comment]
Thanks Jan Willem!
Is this here the correct place to report tickets concerning the FIspace platform?

**Comment by JanWillemKruize** [comment]
yes it is, we will aggregate the questions and send them towards the FIspace team.

**Comment by JanWillemKruize** [comment]
Hi Toni, 

I received some answers! 
1. When accessing the Event Processing Module (EOM Proton) the page keeps reloading every second. This makes it impossible to work with the module. --> The people responsible for this SDK are informed. We hope to respond as soon as possible regarding this issue. 
2. Accessing the Business Collaboration Module fails. The answer I get is: bad request, resource not found.   --> Find here the correct links to use https://bitbucket.org/fispace/core/wiki/Experimentation%20Environment
3. Connecting to the SDI api does not work too. Which URL do I have to use? 
   --> Find here the correct links to use https://bitbucket.org/fispace/core/wiki/Experimentation%20Environment

**Comment by rapw3k** [comment]
@gitoni does that answered your question (for closing the issue?)

**Comment by gitoni** [comment]
Yes, thanks for the answers to the questions 2 and 3. And for reporting question 1.
Though the reloading is still an issue, but it might be cause by my eclipse installation.
Anyway you can close the ticket.
