### ISSUE TITLE
FIspace wizard does not appear

### ISSUE THREAD

**Issue by rapw3k** [SAF2/documentation#7]
S.O: Linux Ubuntu 14.10 Eclipse: Luna (4.2) The FIspace sofware is correctly installed and MVN also. Issue: File > New > Project -> FIspace wizard does not appears in the possible options.

Submitted by Rafael Alcaide

**Comment by rapw3k** [comment]
Answer from Fispace: 

Luna 4.4.2 is not recommended. Use Kepler SR2 instead. See please getting-started-sdk-tutorial (https://bitbucket.org/fispace/apps/wiki/tutorial/getting-started/sdk-tutorial)

Note from Fispace helpdesk: Please remember SMEs to use SAF2 ticketing system to submit FIspace questions. Accelerators are the one contacting Fispace if necessary.

**Comment by ralcaide** [comment]
Hi,

I've installed Kepler SR2 in Linux Ubuntu 14.10  and the FIspace plugins. 
I have still the same problem. 

The version of java is the next one:

java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

In Eclipse Kepler does not appear any option related with FIspace after the installation of the FIspace plugins.

In Windows works perfect but we need Linux for our development.

**Comment by JanWillemKruize** [comment]
We are working on it, hope to provide you an answer as soon as possible!

**Comment by JanWillemKruize** [comment]
Hi, 

we have received an answer:

You probably need jdk 1.8 as you can read in the SDK tutorial, see https://bitbucket.org/fispace/apps/wiki/tutorial/getting-started/sdk-tutorial 

Does this answer help you?

**Comment by ralcaide** [comment]
Hi,

I've update my jdk to 1.8 in Linux Ubuntu and now is working. 
Here you can find the characteristics, maybe it is helpful for other developers:

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

I've found another problems but I will create another issues. This one can be closed. 

Thanks a lot,

Rafa

**Comment by rapw3k** [comment]
Thanks for sharing, I am closing this issue
