### ISSUE TITLE
New project wizard (widget) does not work 

### ISSUE THREAD

**Issue by vangelisv** [SAF2/documentation#8]
iOS 10.8.5, MBP Pro. 
I've installed Fispace SDK (Eclipse Luna, 4.4.2) with Fispace SDK.
When I try File-New-Project-FiSpace type a name, select widget and press Finish, an indicator window appears but it hangs there forever. Project name appears on the Fispace explorer but it is empty!.

**Comment by JanWillemKruize** [comment]
Hi, did you check issue #7 ?

Here they recommend to use Kepler SR2 instead of Luna, 4.4.2

**Comment by vangelisv** [comment]
I worked around it by using FIStudio.
