### ISSUE TITLE
Few technical questions

### ISSUE THREAD

**Issue by maticserc** [SAF2/documentation#9]
Hi, please let me know if I should post the technical questions to some other place. I have a few questions, some more concrete and some more conceptual.

First: FIspace demo environment seems to be down. Are there any timelines when the platform will be re-established?

We have designed the API functionality that our server system will offer towards the other applications on the FIspace platform, as well as functionality that our end-user application will offer towards the others via FIspace platform.

We can't test where and how we will register this functionality (since the platform is down), but please correct me if we're wrong:
1. We will be able to register the API functionality inside FIspace via some module in System & Data Integration module, (or some other module?), is this right? If we're right, is there any link with the details or step-by-step on how to do it, with which specific tool/product/technology/language? Or should we consider some other module for this functionality, or are we getting the concept wrong?
2. There is a mashup (Wirecloud) instance running inside FIspace, as we noticed while it was running. Will it be possible to use the information about API, which will be registered inside FIspace (SDI or some other module from previous question), in the Wirecloud (or are we getting the concept wrong?)? Therefore: if we have an API that provides a certain output in one application, and an API that requires that same output in the other application, is it possible to visualize the instances of both of the applications in the Wirecloud, and connect them? Is there any documentation about how to do this, or is API information not connected with the Wirecloud instance on the FIspace?
3. The authentication system (similar to Keystone/Keyrock) is running inside FIspace, is that right? So basically, we may only develop a client functionality, and use FIspace's authentication module, similarly as we may use FIware Lab's user authentication? Do we understand this right?
4. IF (4) is true, then: Is it possible to create custom attributes in the FISpace's instance of Keystone enabler for a certain users, and save those attributes for our applications inside FIspace's running Keystone instance?
5. Does Orion instance check with the Keystone instance if the user exists when it gets the request with the key from the user? Probably yes?

Thanks, best regards, Matic

**Comment by JanWillemKruize** [comment]
This is indeed the place to ask technical questions. We are working on providing you with clear answers as soon as possible.

**Comment by maticserc** [comment]
Great! Allright, the 1st question I guess we've figured out, we will add the capabilities via FIspace Studio, and then create the business processes via the FIspace developer/business architect sites, right?

**Comment by maticserc** [comment]
Question 3 - tested the approach and it works for us, so we've figured it out as well.

**Comment by JanWillemKruize** [comment]
Thanks for your update. I posted the question at the FIspace page and will close some issues now. Maybe we can have a Skype call later this week to shortly discuss these issues and maybe I can help a bit.

**Comment by maticserc** [comment]
Yes, that would be awesome. I will contact you via LI to schedule something.

**Comment by maticserc** [comment]
Hi Jan Willem and maybe somebody else may help; I have one more question.

We are using FIWARE Lab's instance of OAuth2. We have the following problem:
assuming that {TOKEN} is an actual user's token (a long cryptic string).

1) log-in works well, our callback is called with the ?code={TOKEN} parameter from FIware
2) if we use this token to access the user data with the URL http://account.lab.fi-ware.org/user?access_token={TOKEN}, we get the following message:
{"error":"invalid_token","error_description":"The access token provided is expired, revoked, malformed or invalid for other reasons."}

even though we don't log out or do anything between the log-in and the step "2)".

My other question would be whether we may use the methods, described under http://developer.openstack.org/api-ref-identity-v3.html with FIWARE Lab's authentication system, and if yes, then what to append in front of the URL calls.

Optionally: do the same concepts apply to FIspace's authentication system?

Best,
Matic

**Comment by JanWillemKruize** [comment]
SDI offers a RESTful API to create capabilities:
PUT method to ${server}/sdi/api/capabilities 
Frontend offers an interface to create capabalities (attached presentantion showing how to do it) Diapositiva1.PNG Diapositiva2.PNGDiapositiva3.PNGDiapositiva4.PNGDiapositiva5.PNGDiapositiva6.PNG
SDK provides a plugin to create capabilities (https://bitbucket.org/fispace/apps/wiki/tutorial/getting-started/sdk-tutorial) (https://bitbucket.org/fispace/apps/wiki/tutorial/getting-started/sdk-tutorial/how_to_use_capmodel_plugin)
In case you are developing using Java technology, you can use ygg also to create and manage capabilities

**Comment by JanWillemKruize** [comment]
for a more complete answer please check this link: 

https://bitbucket.org/fispace/phase3support/issue/9/registration-of-api-functionality

**Comment by rapw3k** [comment]
@maticserc we received answer from FIWARE-lab team:

"the item you are calling TOKEN is not the OAauth2 access token yet. This is the code your application has to user in order to create it. Pleas, take a look at https://github.com/ging/fi-ware-idm/wiki/Using-the-FI-LAB-instance"

**Comment by maticserc** [comment]
Hi rapw3k, thank you for the answer, we've fixed that one already recently. I think we may close this ticket, because we've cleaned up all of the questions.
